### ISSUE TITLE
rest api 方式每次只能传递一条 sql 语句

### ISSUE THREAD

**Issue by codedever** [maikebing/Maikebing.EntityFrameworkCore.Taos#1]
如题: 我使用你写的这个库做了测试, 发现每次只能传递一条sql语句, 无聊是 insert into 还是 import into, 这样的话, 对于设备频繁上送的报文, 使用 rest api 一遍遍的调用怕是性能还不如传统的关系型数据库了!
这个问题是, TDengine 本身rest api每次只能接受一条 sql 语句还是什么您的库的问题了?

**Comment by hjxilinx** [comment]
TD支持通过一条SQL语句进行批量写入。但是对于jdbc中的addbatch/executeBatch这种API支持还不太好。最近就会增加提供对JDBC批量写入的支持。

**Comment by maikebing** [comment]
库本身没有做任何限制。
