### ISSUE TITLE
怎么使用时间聚合函数INTERVAL

### ISSUE THREAD

**Issue by TangPe** [maikebing/Maikebing.EntityFrameworkCore.Taos#113]
select first(value) from iot_datas where ts>'2021-06-09 10:01:00' and ts<'2021-06-09 11:00:00'  and tbname in ('iot_data_319400013') INTERVAL(9m,4m) FILL(NULL) limit 10;
这种sql怎么通过linq写，或者是其他方式实现

**Comment by maikebing** [comment]
我们对ef只是试探性的， 支持的效果并不好

**Comment by maikebing** [comment]
因为小众， td的用户少， 所以， 目前没更多的想法
