### ISSUE TITLE
接口方法把taos数据库对微秒级的支持强行改成了毫秒级

### ISSUE THREAD

**Issue by lucienbao** [maikebing/Maikebing.EntityFrameworkCore.Taos#132]
https://github.com/maikebing/Maikebing.EntityFrameworkCore.Taos/blob/85fc923a57f88ea3533628281af16f347296c460/src/Maikebing.Data.Taos/TaosDataReader.cs#L631

**Comment by lucienbao** [comment]
private DateTime GetDateTimeFrom(IntPtr data)
        {
            var val = Marshal.ReadInt64(data);
            //double tsp;
            //var _dateTimePrecision = (TSDB_TIME_PRECISION)TDengine.ResultPrecision(_taosResult);
            //if (_dateTimePrecision == TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MICRO)
            //{
            //    tsp = (val / 1000);
            //}
            //else
            //{
            //    tsp = val;
            //}
            //if (tsp > _date_max_1970)
            //{
            //    //fix https://github.com/taosdata/TDengine/issues/3270
            //    tsp /= 1000;
            //}
            //var v9 = _dt1970.AddMilliseconds(tsp);
            var v9 = _dt1970.AddTicks(val * 10);
            return v9.ToLocalTime();
        }

**Comment by lucienbao** [comment]
另外TaosCommand.cs 319行的写法也有问题，具体参见http://www.tdengine.com/cn/documentation/taos-sql 中“插入一条或多条记录”小节下方的“注意”小节的内容提示。

**Comment by lucienbao** [comment]
在TaosDataReader 307行

       public virtual TimeSpan GetTimeSpan(int ordinal)
        {
            var val = Marshal.ReadInt64(GetValuePtr(ordinal));
            var _dateTimePrecision = (TSDB_TIME_PRECISION)TDengine.ResultPrecision(_taosResult);
            switch (_dateTimePrecision)
            {
             /*
             * ticks为100纳秒，必须乘以10才能达到微秒级的区分度
             * 1秒s    = 1000毫秒ms
             * 1毫秒ms = 1000微秒us
             * 1微秒us = 1000纳秒ns
             * 因此， 1毫秒ms = 1000000纳秒ns = 10000ticks
             */
                case TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_NANO:
                    return TimeSpan.FromTicks(val / 100);
                case TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MICRO:
                    return TimeSpan.FromTicks(val * 10);
                case TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MILLI:
                default:
                    return TimeSpan.FromTicks(val * 10000);
            }
            //if (_dateTimePrecision == TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MICRO)
            //{
            //    return TimeSpan.FromMilliseconds(val / 1000);
            //}
            //else
            //{
            //    return TimeSpan.FromMilliseconds(val);
            //}
        }

**Comment by lucienbao** [comment]
在TaosDataReader 648行

       private DateTime GetDateTimeFrom(IntPtr data)
        {
            var val = Marshal.ReadInt64(data);
            //double tsp;
            var _dateTimePrecision = (TSDB_TIME_PRECISION)TDengine.ResultPrecision(_taosResult);
            switch (_dateTimePrecision)
            {
                /*
                * ticks为100纳秒，必须乘以10才能达到微秒级的区分度
                * 1秒s    = 1000毫秒ms
                * 1毫秒ms = 1000微秒us
                * 1微秒us = 1000纳秒ns
                * 因此， 1毫秒ms = 1000000纳秒ns = 10000ticks
                */
                case TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_NANO:
                    val /= 100;
                    break;
                case TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MICRO:
                    val *= 10;
                    break;
                case TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MILLI:
                default:
                    val *= 10000;
                    break;
            }
            //if (_dateTimePrecision == TSDB_TIME_PRECISION.TSDB_TIME_PRECISION_MICRO)
            //{
            //    tsp = (val / 1000);
            //}
            //else
            //{
            //    tsp = val;
            //}
            //if (tsp > _date_max_1970)
            //{
            //    //fix https://github.com/taosdata/TDengine/issues/3270
            //    tsp /= 1000;
            //}
            //var v9 = _dt1970.AddMilliseconds(tsp);
            var v9 = _dt1970.AddTicks(val);
            return v9.ToLocalTime();
        }

**Comment by maikebing** [comment]
已经修订。
