### ISSUE TITLE
建议 EnsureCreated 使用语句 IF NOT EXISTS

### ISSUE THREAD

**Issue by ghost** [maikebing/Maikebing.EntityFrameworkCore.Taos#21]
我看源码是检测 table 或者 database 是否已经存在，如果存在则不创建，不存在则创建。但是我发现再执行时我这里存在几个问题。

数据库服务我装的是 docker 版本 1.6.5.9

1. 建库或者建表的时候直接使用 IF NOT EXISTS 语句来建，数据库本身会自动检测是否存在，不存在则建表。我通过你的接口发现 SHOW DATABASES 能获取到表的原始数据，但是反序列化后所有为 string 的字段结果为 null，如： name 与 status，但是 stable 这些能获取到正确的数值。所以导致你在检测库是否存在的时候出现错误，也就是明明存在库，你获取不到库的名称。

2. 不知道你是否存在这种故障，建完库与表之后，后面的插入语句无法执行，提示已经与数据库断开了。

还有一个疑问就是，因为我不懂，请问使用 taos.dll 引用方式在 linux 平台可以使用吗？因为在我的思维里面貌似 NF 才能引用 win32 的dll，linux 下的库应该与 win 下不一样吧。

**Comment by maikebing** [comment]
> 还有一个疑问就是，因为我不懂，请问使用 taos.dll 引用方式在 linux 平台可以使用吗？因为在我的思维里面貌似 NF 才能引用 win32 的dll，linux 下的库应该与 win 下不一样吧。
Linux 会自动匹配使用so文件， 同事会区分32 或者 64位
