### ISSUE TITLE
求大神及时更新到1.6.6

### ISSUE THREAD

**Issue by lizhuming** [maikebing/Maikebing.EntityFrameworkCore.Taos#24]
由于现在这个arm架构的刚刚支持1.6.6，发现调用的时候存在问题，连接不上，

**Comment by wxlevel** [comment]
服务端安装的是 TDengine-server-1.6.6.2-Linux-x64-beta 的版本，启动时，说客户端与服务端的版本不一致，目前.net 的taos.dll 是支持什么版本？？

**Comment by maikebing** [comment]
1.6.5.9
