### ISSUE TITLE
我只想用 efcore，是必须要同时安装Maikebing.EntityFrameworkCore.Taos和Maikebing.Data.Taos吗？

### ISSUE THREAD

**Issue by wxlevel** [maikebing/Maikebing.EntityFrameworkCore.Taos#35]
我只想用 efcore，是必须要同时安装Maikebing.EntityFrameworkCore.Taos和Maikebing.Data.Taos吗？

**Comment by maikebing** [comment]
Maikebing.EntityFrameworkCore.Taos  会引用  Maikebing.Data.Taos
