### ISSUE TITLE
涛思数据库超级表对应表新增异常

### ISSUE THREAD

**Issue by kingflyok** [maikebing/Maikebing.EntityFrameworkCore.Taos#40]
涛思数据库超级表对应表新增异常
![image](https://user-images.githubusercontent.com/29110971/93068144-ae770700-f6ae-11ea-95b6-0de37f8e63e6.png)

**Comment by kingflyok** [comment]
我涛思版本是 2.0.3.1

**Comment by maikebing** [comment]
调用事务了？先别调用事务试试看， 或者你有报错的例子么？我测试一下？
