### ISSUE TITLE
项目中包含的taos.dll,taos.so文件好像没有作用，是否可以去掉？

### ISSUE THREAD

**Issue by rennner** [maikebing/Maikebing.EntityFrameworkCore.Taos#51]
现在涛思官方提供的客户端驱动要求必须服务器版本唯一匹配，而项目中包含的驱动库taos.dll(.so) 好像也没有什么用，是否可以考虑从项目中去掉并且自动从驱动安装目录中加载？

**Comment by maikebing** [comment]
这样的话确实需要去掉。
