### ISSUE TITLE
为何我在使用ADO.NET查询数据时，数据已查询出来在程序中却获取不到

### ISSUE THREAD

**Issue by 1316279031** [maikebing/Maikebing.EntityFrameworkCore.Taos#90]
![image](https://user-images.githubusercontent.com/53509893/113667804-e2b22380-96e3-11eb-814c-5e3452900858.png)
以下是我的代码
`using (var connection = new TaosConnection(builder.ConnectionString))
            {
                connection.Open();
                var cmd_select = connection.CreateCommand();
                cmd_select.CommandText = $"select last_row(*) from {_tdengineConfig.DbName}.{tableName}";
                using (var reader = cmd_select.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            foreach (var item in codes)
                            {
                                ls.Add(item, reader[item]);
                            }
                        }
                    }
                }
            }`

**Comment by maikebing** [comment]
这个bug已经修复
